### ISSUE TITLE
RuntimeError: no valid convolution algorithms available in CuDNN

### ISSUE THREAD

**Issue by mmsx** [gistvision/e2sri#13]
When I run `python test.py --data_dir ../dataset/slider_depth --checkpoint_path ../save_dir/2x_7s.pth --save_dir ../save_dir`, it remind me that `RuntimeError: no valid convolution algorithms available in CuDNN`, I don't know what's wrong with it. Could you please help me?

**Comment by mmsx** [comment]
I solve it……the editor of pytorch is not suit for cuda.

**Comment by ucalyptus2** [comment]
@mmsx can u explain what u meant.
