### ISSUE TITLE
Training Code 

### ISSUE THREAD

**Issue by ercanburak** [gistvision/e2sri#3]
Hi, thanks for your work.

Do you still intend to share the training codes as written in [readme](https://github.com/gistvision/e2sri/blob/master/README.md#training)?

If so, when will it be available?

**Comment by ercanburak** [comment]
Can you please check this? @smmmmi @jchoigist

**Comment by smmmmi** [comment]
Thank you for your interest in our code @ercanburak . This work is currently under publication, we will update the repo after that.

**Comment by WarranWeng** [comment]
Could you please release your training codes? @smmmmi

**Comment by ercanburak** [comment]
Any updates on this? @smmmmi @jchoigist

**Comment by ercanburak** [comment]
Any updates? @smmmmi @jchoigist

**Comment by smmmmi** [comment]
Thank you for the follow-up @ercanburak .
Yes, I will try to clean up and upload in a week or so.

**Comment by ChidanandKumarKS** [comment]
@smmmmi , @jchoigist 
Awaiting for the training codes

**Comment by smmmmi** [comment]
The training code is released. I hope you can use the training code for your research: @ercanburak @WarranWeng @ChidanandKumarKS

**Comment by ChidanandKumarKS** [comment]
@smmmmi  Thanks for sharing. It helps a lot
