### ISSUE TITLE
training dataset

### ISSUE THREAD

**Issue by Jee-King** [gistvision/e2sri#5]
Hi, thanks for your great work!

Could you please release your training datasets?

**Comment by smmmmi** [comment]
Hi @Jee-King,

Please be noted as the dataset is very large we have hosting issues so it may not be easily possible to share the dataset.
However, if you follow the [ESIM](https://github.com/uzh-rpg/rpg_esim) simulator on planar event generation you can generate a mostly similar dataset with the given snippets attached (credits go to the ESIM authors).

[Dataset_E2SRI.zip](https://github.com/gistvision/e2sri/files/6513119/Dataset_E2SRI.zip)
